### ISSUE TITLE
Create typescript definitions

### ISSUE THREAD

**Issue by ozyman42** [npm/validate-npm-package-name#24]
This could either be part of the main package in a .d.ts file or as a separate package under the @types scope.

**Comment by ExE-Boss** [comment]
Packages in&nbsp;the&nbsp;@npm&nbsp;organisation generally&nbsp;don’t&nbsp;have **TypeScript**&nbsp;type&nbsp;definitions.

Instead, you&nbsp;should&nbsp;use the&nbsp;[`@types/validate‑npm‑package‑name`](https://www.npmjs.com/package/@types/validate-npm-package-name)&nbsp;package to&nbsp;supply the&nbsp;type&nbsp;definitions.

**Comment by wraithgar** [comment]
We don't typically include typescript definitions in these packages because we don't have a good process for updating them  internally.  If you feel you want to take on this responsibility you can take that on through the [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package)
