### ISSUE TITLE
[BUG] "download" is not an allowed word in the package name

### ISSUE THREAD

**Issue by oliviertassinari** [npm/validate-npm-package-name#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`validateNpmPackageName("@react-cdk/core-internal-download")` returns:

```js
{
  "validForNewPackages": true,
  "validForOldPackages": true
}
```

https://codesandbox.io/s/brave-engelbart-8vg1fc?file=/src/App.js

### Expected Behavior

`validateNpmPackageName("@react-cdk/core-internal-download")` returns:

```js
{
  "validForNewPackages": false,
  "validForOldPackages": true
}
```

### Steps To Reproduce

1. Create this package

```json
{
  "name": "@react-cdk/core-internal-download",
  "private": false,
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "publishConfig": {
    "access": "public"
  },
  "author": "",
  "license": "ISC"
}
```

2. try to publish it

> npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/@react-cdk%2fcore-internal-download - Bad Request

3. Change the name, it works https://www.npmjs.com/package/@react-cdk/internal-lab

The 400 error code is confusing, could we get a clearer error message? Also, https://docs.npmjs.com/package-name-guidelines is not giving tips on what's going on. The issue seems to be with the word: `download`.

### Environment

- npm: 8.11.0
- Node: v16.16.0
- OS: macOS 12
- platform: Macbook Pro

**Comment by wraithgar** [comment]
This is due to a disconnect between what the npm cli does to validate package names, and what the npm registry does.  They are slightly different, the npm registry being the less permissive of the two.

The npm cli supports multiple registries, some of which may allow this.  So we can't change this repo to prohibit it without a (probably unnecessary) breaking change.

This library is in the grey area of being client-side input validation, which is always a "nice to have" but usually defers to letting some error states be reported by the server instead, which is what's happening here.

As far as changing the 400 code's messaging, that is something that would have to change on the npm registry itself, not the npm cli. npm just shows you whatever the registry responds with.

npm registry support is at https://www.npmjs.com/support

**Comment by oliviertassinari** [comment]
@wraithgar Thanks for the udpate. True, my feedback is definitely related to the npm registry. I wanted to raise our frustration in the hope that 1. other developers will be able to find this issue 2. npm would become aware of the DX opportunity.

Now, It's not important enough for us to open a private support case. So I will leave it here.
